### ISSUE TITLE
Should handle xx:xx notation for already spent time

### ISSUE THREAD

**Issue by mastilver** [mvalipour/onetime-cli#1]
https://github.com/mvalipour/onetime-cli/blob/master/src/commands/time/_base.js#L168

**Comment by mvalipour** [comment]
This is now supported. (https://github.com/mvalipour/onetime-cli/commit/e8e8d30c7f5cdca6e57fabf42fdc2ffd83f7ea46) Will be included in the next release

**Comment by mastilver** [comment]
:+1:
