### ISSUE TITLE
time prefix is verbose

### ISSUE THREAD

**Issue by hisuwh** [mvalipour/onetime-cli#13]
time management is the main focus of this utility and as such I feel like typing "onetime time" every time you want to do something is quite verbose.

Could the time related tasks not live off of onetime?  or at least can we have a shorthand, ie "t"

**Comment by mvalipour** [comment]
Could you please put this on consensus in the skype group? I kinda agree with you and noticed this from the beginning but not sure how plausible it is to change it.

**Comment by mvalipour** [comment]
@hisuwh 

[v1.6](https://github.com/mvalipour/onetime-cli/releases/tag/v1.6.0)

I've introduced alias `t` for `time`, so now this should be enough to close this issue :)
