### ISSUE TITLE
Be able to use alias with resume

### ISSUE THREAD

**Issue by hisuwh** [mvalipour/onetime-cli#14]
E.g.:

> onetime time resume -a devman

**Comment by mvalipour** [comment]
Hmmm not sure I understand. When resuming, you would want to un-pause one of your times. Aliases are used for when you want to avoid entering project/task, etc.

**Comment by hisuwh** [comment]
Well with dev management for example I switch back to it several times during the day
I don't want to necessarily have more than one entry for it.

To start it I can I do onetime time start -a aliesname

But to resume it I have the do onetime time resume, then select it, then press enter

I don't know if there is a way that can be streamlined for often used tasks

**Comment by mvalipour** [comment]
Interesting,

So what we need to do is to use the alias to "filter" your times and ask you to select, and of course if there is only one (your scenario) take it and don't ask
