### ISSUE TITLE
Issue with onetime time restart 

### ISSUE THREAD

**Issue by tarunvd** [mvalipour/onetime-cli#4]
onetime time restart -o 1

On running the above a timesheet entry was created on Harvest but the timer was in stopped state with time = 0.0

 The timer needs to start.

**Comment by mvalipour** [comment]
I don't seem to be able to replicate this.
Are you sure you didn't put anything for the `time` when restarting?

**Comment by mvalipour** [comment]
@tarunvd Have you experienced this recently? If not we can close this.

**Comment by mvalipour** [comment]
I'm going to close this since I heard no more complains about this.
